"""
Synapsis Agents - Prompts
=========================
System prompts and templates for all LLM agents.
"""

from .prompts import (
    # Query Planner
    QUERY_PLANNER_SYSTEM,
    QUERY_PLANNER_USER,
    # Reasoner
    REASONER_SYSTEM,
    REASONER_USER,
    REASONER_FOLLOWUP,
    # Critic
    CRITIC_SYSTEM,
    CRITIC_USER,
    # Entity Extraction
    ENTITY_EXTRACTION_SYSTEM,
    ENTITY_EXTRACTION_USER,
    # Summarization
    SUMMARIZER_SYSTEM,
    SUMMARIZER_USER,
    # Proactive
    CONNECTION_DISCOVERY_SYSTEM,
    CONTRADICTION_DETECTION_SYSTEM,
    DIGEST_SYSTEM,
    DIGEST_USER,
    # Abstention
    ABSTENTION_NO_SOURCES,
    ABSTENTION_LOW_CONFIDENCE,
    ABSTENTION_CONTRADICTIONS,
)

__all__ = [
    "QUERY_PLANNER_SYSTEM",
    "QUERY_PLANNER_USER",
    "REASONER_SYSTEM",
    "REASONER_USER",
    "REASONER_FOLLOWUP",
    "CRITIC_SYSTEM",
    "CRITIC_USER",
    "ENTITY_EXTRACTION_SYSTEM",
    "ENTITY_EXTRACTION_USER",
    "SUMMARIZER_SYSTEM",
    "SUMMARIZER_USER",
    "CONNECTION_DISCOVERY_SYSTEM",
    "CONTRADICTION_DETECTION_SYSTEM",
    "DIGEST_SYSTEM",
    "DIGEST_USER",
    "ABSTENTION_NO_SOURCES",
    "ABSTENTION_LOW_CONFIDENCE",
    "ABSTENTION_CONTRADICTIONS",
]
